// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 trace.protocol.
// Portions derived from an Apache-2.0 licensed upstream; see NOTICE.

//! Operator tool: emit TowerHash's constants as a CUDA header.
//!
//! Every value a GPU miner needs is derived here from the Rust implementation
//! that consensus actually uses, and printed as C. Nothing is transcribed by
//! hand: a single mistyped nibble in a 128-bit constant produces a miner that
//! hashes *almost* correctly, finds nothing a node accepts, and reports no
//! error at all.
//!
//! Everything is emitted already converted to the **flat (GCM) basis**, which
//! is the basis the permutation runs in, so the kernel never converts a
//! constant at runtime — only its inputs and its output.
//!
//! ```text
//! cargo test --release -p elide_poseidon2b --test emit_cuda_constants \
//!   -- --ignored --nocapture > elide_pow_constants.cuh
//! ```

use elide_core::hardware::{flat_to_tower_u128, tower_to_flat_u128};
use elide_poseidon2b::native::domain::{capacity_iv, TAG_POWHDR};
use elide_poseidon2b::native::permutation::{
    F_ROUNDS, MDS_FULL, MDS_PARTIAL, N_ROUNDS, P_ROUNDS, ROUND_CONSTANTS, SBOX_EXPONENT, STATE_SIZE,
};

/// `{ lo, hi }` initialiser for the driver's `F128`.
fn f128(value: u128) -> String {
    format!("{{0x{:016x}ULL,0x{:016x}ULL}}", value as u64, (value >> 64) as u64)
}

/// The basis conversion is linear over GF(2), so a 32×16 nibble table is
/// enough: table[chunk][nibble] is the image of `nibble << (4*chunk)`.
fn nibble_table(convert: impl Fn(u128) -> u128) -> Vec<u128> {
    let mut table = Vec::with_capacity(32 * 16);
    for chunk in 0..32u32 {
        for nibble in 0..16u128 {
            table.push(convert(nibble << (4 * chunk)));
        }
    }
    table
}

fn emit_table(name: &str, values: &[u128]) {
    println!("__device__ __constant__ F128 {name}[{}] = {{", values.len());
    for row in values.chunks(4) {
        let cells: Vec<String> = row.iter().map(|v| f128(*v)).collect();
        println!("  {},", cells.join(", "));
    }
    println!("}};\n");
}

#[test]
#[ignore = "operator tool; writes a CUDA header to stdout"]
fn emit_cuda_constants() {
    println!("// SPDX-License-Identifier: Apache-2.0");
    println!("// Copyright (C) 2026 trace.protocol.");
    println!("//");
    println!("// GENERATED by elide_poseidon2b/tests/emit_cuda_constants.rs — do not edit.");
    println!("// Every constant is already in the flat (GCM) basis.");
    println!("#pragma once\n");

    println!("#define TH_STATE_SIZE {STATE_SIZE}");
    println!("#define TH_F_ROUNDS   {F_ROUNDS}");
    println!("#define TH_P_ROUNDS   {P_ROUNDS}");
    println!("#define TH_N_ROUNDS   {N_ROUNDS}");
    println!("#define TH_SBOX_EXP   {SBOX_EXPONENT}\n");

    // Capacity IV for the PoW domain, flat basis.
    let iv = capacity_iv(TAG_POWHDR);
    println!("__device__ __constant__ F128 IV_FLAT[2] = {{");
    println!(
        "  {}, {}",
        f128(tower_to_flat_u128(iv[0].0)),
        f128(tower_to_flat_u128(iv[1].0))
    );
    println!("}};\n");

    // Round constants, flat basis, [lane][round].
    println!("__device__ __constant__ F128 RC_FLAT[{STATE_SIZE}][{N_ROUNDS}] = {{");
    for lane in ROUND_CONSTANTS.iter() {
        println!("  {{");
        for row in lane.chunks(4) {
            let cells: Vec<String> = row.iter().map(|v| f128(tower_to_flat_u128(*v))).collect();
            println!("    {},", cells.join(", "));
        }
        println!("  }},");
    }
    println!("}};\n");

    // MDS matrices, flat basis, plus the "entry is exactly one" masks the
    // reference uses to skip a multiplication.
    for (name, matrix) in [("MDS_FULL_FLAT", &MDS_FULL), ("MDS_PARTIAL_FLAT", &MDS_PARTIAL)] {
        println!("__device__ __constant__ F128 {name}[{STATE_SIZE}][{STATE_SIZE}] = {{");
        for row in matrix.iter() {
            let cells: Vec<String> = row.iter().map(|v| f128(tower_to_flat_u128(*v))).collect();
            println!("  {{ {} }},", cells.join(", "));
        }
        println!("}};");
        println!("__device__ __constant__ int {name}_IS_ONE[{STATE_SIZE}][{STATE_SIZE}] = {{");
        for row in matrix.iter() {
            let cells: Vec<String> = row.iter().map(|v| i32::from(*v == 1).to_string()).collect();
            println!("  {{ {} }},", cells.join(", "));
        }
        println!("}};\n");
    }

    // Straight-line MDS application with the constants as literals.
    //
    // Going through a __constant__ array hides the values from the compiler, so
    // every product is a full 128x128 carry-less multiply. Emitting them inline
    // lets nvcc constant-fold the operand masks inside clmul32 — and the MDS is
    // about two thirds of all the multiplies in a permutation.
    for (name, matrix) in [("mds_full_apply", &MDS_FULL), ("mds_partial_apply", &MDS_PARTIAL)] {
        println!("__device__ __forceinline__ void {name}(F128* s) {{");
        println!("  F128 a = s[0], b = s[1], c = s[2], d = s[3];");
        let lanes = ["a", "b", "c", "d"];
        for (i, row) in matrix.iter().enumerate() {
            let mut terms: Vec<String> = Vec::new();
            for (j, entry) in row.iter().enumerate() {
                if *entry == 1 {
                    terms.push(lanes[j].to_string());
                } else {
                    let flat = tower_to_flat_u128(*entry);
                    terms.push(format!("fmul({}, (F128){})", lanes[j], f128(flat)));
                }
            }
            let mut expr = terms[0].clone();
            for term in &terms[1..] {
                expr = format!("fx({expr}, {term})");
            }
            println!("  s[{i}] = {expr};");
        }
        println!("}}\n");
    }

    // Host-side row table: the image of each basis bit. The device tables above
    // live in __constant__ memory, which host code cannot read, so the driver
    // needs its own copy to convert a template's fields before upload.
    println!("static const F128 T2F_ROW_H[128] = {{");
    for row in (0..128u32).collect::<Vec<_>>().chunks(4) {
        let cells: Vec<String> = row
            .iter()
            .map(|bit| f128(tower_to_flat_u128(1u128 << bit)))
            .collect();
        println!("  {},", cells.join(", "));
    }
    println!("}};\n");

    emit_table("TOWER_TO_FLAT_NIB", &nibble_table(tower_to_flat_u128));
    emit_table("FLAT_TO_TOWER_NIB", &nibble_table(flat_to_tower_u128));
}

/// The nibble decomposition must reproduce the reference conversion exactly.
/// This runs in the normal suite: if it ever fails, every emitted header is
/// wrong and so is every miner built from one.
#[test]
fn nibble_tables_reproduce_the_reference_conversion() {
    let to_flat = nibble_table(tower_to_flat_u128);
    let to_tower = nibble_table(flat_to_tower_u128);

    let mut seed = 0x243F_6A88_85A3_08D3u64;
    let mut next = || {
        seed ^= seed << 13;
        seed ^= seed >> 7;
        seed ^= seed << 17;
        seed
    };

    for _ in 0..2_000 {
        let value = (u128::from(next()) << 64) | u128::from(next());

        let mut flat = 0u128;
        let mut tower = 0u128;
        let mut remaining = value;
        for chunk in 0..32 {
            let nibble = (remaining & 0xF) as usize;
            flat ^= to_flat[chunk * 16 + nibble];
            tower ^= to_tower[chunk * 16 + nibble];
            remaining >>= 4;
        }

        assert_eq!(flat, tower_to_flat_u128(value), "tower->flat for {value:#x}");
        assert_eq!(tower, flat_to_tower_u128(value), "flat->tower for {value:#x}");
        // And the two directions must be inverses.
        assert_eq!(flat_to_tower_u128(flat), value, "round trip for {value:#x}");
    }
}
