[package]
name = "elide_block"
version.workspace = true
edition = "2021"
license = "Apache-2.0"

[dependencies]
elide_core       = { path = "../elide_core" }
elide_poseidon2b = { path = "../elide_poseidon2b" }
elide_tx         = { path = "../elide_tx" }
elide_gkr        = { path = "../elide_gkr" }
elide_chain      = { path = "../elide_chain" }
elide_recursive  = { path = "../elide_recursive" }
