[package]
name = "noid_poseidon2b"
version.workspace = true
edition = "2021"

[dependencies]
noid_core = { path = "../noid_core" }
rayon = "1.10"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
zeroize = { version = "1.8", features = ["zeroize_derive"] }
bech32 = "0.11"
hex    = "0.4"

[dev-dependencies]
static_assertions = "1.1"
