[package]
name = "elide_recursive"
version.workspace = true
edition = "2021"

[dependencies]
elide_core = { path = "../elide_core" }
elide_poseidon2b = { path = "../elide_poseidon2b" }
elide_chain = { path = "../elide_chain" }
elide_tx = { path = "../elide_tx" }
elide_gkr = { path = "../elide_gkr" }
elide_fri = { path = "../elide_fri" }
elide_fri_binius = { path = "../elide_fri_binius" }
elide-ivc-core = { path = "../elide_ivc_core" }
elide-ivc-prover = { path = "../elide_ivc_prover" }
rayon = "1"
serde = { version = "1", features = ["derive"] }
bincode = "1"
tracing = { workspace = true }
